#' Plot minimum spanning tree (MST)
#' 
#' Plot minimum spanning tree (MST) from FlowSOM clustering
#' 
#' Saves a minimum spanning tree (MST) plot, which shows the hierarchical relationship 
#' between clusters detected by FlowSOM. Point sizes are scaled to represent cluster sizes
#' (number of cells per cluster).
#' 
#' 
#' @param d_se Data object in \code{\link[SummarizedExperiment]{SummarizedExperiment}} 
#'   format. Must contain a column of cluster labels in the row meta-data, and a minimum 
#'   spanning tree (MST) object in the experiment meta-data, as generated by 
#'   \code{\link{generateClusters}}.
#' 
#' @param path Path to save plot. Default = "." (current working directory).
#' 
#' @param filename Filename to save plot.
#' 
#' @param ... Additional arguments to pass to \code{plot}.
#' 
#' 
#' @importFrom grDevices pdf
#' @importFrom graphics plot
#' @importFrom S4Vectors metadata
#' 
#' @export
#' 
#' @seealso \code{\link{testDA}} \code{\link{testDE_med}} \code{\link{testDE_FDA}}
#'
#' @examples
#' # See full examples in testing functions: testDA, testDE_med, testDE_FDA
#' 
plotMST <- function(d_se, path = ".", filename = "plot_MST.pdf", ...) {
  
  mst <- metadata(d_se)$MST
  
  # [to do: change to ggplot2; generalize formatting]
  pdf(file.path(path, filename), width = 7, height = 7)
  plot(mst$l, cex = (mst$size - 7.5) / 3, pch = 19)
  dev.off()
}


