#' Plot minimum spanning trees (MST)
#' 
#' Plot minimum spanning trees (MST) from FlowSOM clustering, with optional color shading 
#' to represent differential test results
#' 
#' Creates one or more minimum spanning tree (MST) plots, which show the relationship
#' between clusters generated by FlowSOM. Optionally, points can be shaded to represent 
#' differential test results.
#' 
#' The \code{type} argument specifies the type of MST plots to generate. Options are:
#' \itemize{
#' \item \code{basic} Basic MST plot without any differential test results.
#' \item \code{DA} MST plot with shading to represent results from tests for differential 
#' abundance (DA) of clusters.
#' \item \code{DE} MST plots with shading to represent results from tests for differential
#' expression (DE) of functional markers within clusters. One MST plot is generated for 
#' each marker, displayed on multiple panels.
#' }
#' 
#' In each case, point sizes are also scaled to represent the total number of cells per 
#' cluster (across all samples).
#' 
#' 
#' @param d_se Data object from \code{\link{generateClusters}}, which contains the minimum
#'   spanning tree (MST) information from the FlowSOM clustering algorithm.
#' 
#' @param d_counts Data object from \code{\link{calcCounts}}, which contains the number of
#'   cells per cluster.
#' 
#' @param res_DA Results object from the differential abundance (DA) testing function
#'   (\code{\link{testDA}}). Required if \code{type = DA}. Default = NULL.
#' 
#' @param res_DE Results object from one of the differential expression (DE) testing
#'   functions (\code{\link{testDE_med}}, \code{\link{testDE_FDA}},
#'   \code{\link{testDE_KS}}, or \code{\link{testDE_LM}}). Required if \code{type = DE}.
#'   Default = NULL.
#' 
#' @param type Type of MST plot to generate. Options are "basic" (no differential test 
#'   results), "DA" (shading to represent DA test results), "DE" (shading to represent DE
#'   test results). Default = "basic".
#' 
#' @param path Path to save plot. Default = current working directory.
#' 
#' 
#' @importFrom S4Vectors metadata
#' @importFrom SummarizedExperiment rowData
#' @importFrom scales trans_new
#' @importFrom ggplot2 ggplot aes geom_point coord_fixed facet_wrap scale_size 
#'   scale_color_gradient ggtitle theme_bw ggsave
#' 
#' @export
#' 
#' @seealso \code{\link{testDA}} \code{\link{testDE_med}} \code{\link{testDE_FDA}}
#'   \code{\link{testDE_KS}} \code{\link{testDE_LM}}
#'
#' @examples
#' # See full examples in testing functions: testDA, testDE_med, testDE_FDA, testDE_KS,
#' # testDE_LM
#' 
plotMST <- function(d_se, d_counts, res_DA = NULL, res_DE = NULL, 
                    type = c("basic", "DA", "DE"), path = ".") {
  
  mst <- metadata(d_se)$MST
  mst_coords <- mst$l
  
  if (!(nrow(mst_coords) == length(rowData(d_counts)$cluster))) {
    stop("minimum spanning tree (MST) does not have correct number of clusters")
  }
  
  n_cells <- rowData(d_counts)$n_cells
  
  d_plot <- data.frame(mst_coords, n_cells)
  colnames(d_plot) <- c("MST_x", "MST_y", "n_cells")
  
  if (!(type == "basic")) {
    # transformation for displaying p-values
    nroot_trans <- function() {
      trans_new("nroot", function(x) x^(1/10), function(x) x^10)
    }
  }
  
  if (type == "basic") {
    ggplot(d_plot, aes(x = MST_x, y = MST_y, size = n_cells)) + 
      geom_point(alpha = 0.5, color = "darkblue") + 
      coord_fixed() + 
      ggtitle("FlowSOM clustering: Minimum spanning tree (MST)") + 
      theme_bw()
    
    ggsave(file.path(path, "MST_basic.pdf"), width = 7, height = 7)
  }
  
  if (type == "DA") {
    if (is.null(res_DA)) stop("'res_DA' object must be provided if 'type == 'DA''")
    
    p_adj_DA <- rowData(res_DA)$adj.P.Val
    d_plot <- cbind(d_plot, p_adj = p_adj_DA)
    
    min_val <- min(p_adj_DA)
    max_val <- max(p_adj_DA)
    
    ggplot(d_plot, aes(x = MST_x, y = MST_y, size = n_cells, color = p_adj)) + 
      geom_point(alpha = 0.75) + 
      scale_color_gradient(low = "orange", high = "gray60", trans = nroot_trans(), 
                           breaks = c(min_val, 0.05, max_val), 
                           labels = c(round(min_val), 0.05, round(max_val))) + 
      coord_fixed() + 
      ggtitle("MST: Differential abundance (DA) test results") + 
      theme_bw()
    
    ggsave(file.path(path, "MST_results_DA.pdf"), width = 7, height = 7)
  }
  
  if (type == "DE") {
    if (is.null(res_DE)) stop("'res_DE' object must be provided if 'type == 'DE''")
    
    # column name of adjusted p-values
    col_p_adj <- colnames(rowData(res_DE))[which(colnames(rowData(res_DE)) %in% c("p_adj", "adj.P.Val"))]
    
    n_markers <- length(table(rowData(res_DE)$marker))
    d_plot_rep <- do.call("rbind", rep(list(d_plot), n_markers))
    
    d_plot <- cbind(rowData(res_DE)[, c("n_cells", "marker", col_p_adj)], 
                    d_plot_rep[, c("MST_x", "MST_y")])
    
    # give consistent name to column with adjusted p-values
    colnames(d_plot)[match(col_p_adj, colnames(d_plot))] <- "p_adj"
    
    d_plot <- as.data.frame(d_plot)
    
    ggplot(d_plot, aes(x = MST_x, y = MST_y, size = n_cells, color = p_adj)) + 
      geom_point(alpha = 0.5) + 
      facet_wrap(~ marker) + 
      scale_size(range = c(0, 3)) + 
      scale_color_gradient(low = "red", high = "gray50", trans = nroot_trans(), 
                           breaks = c(min_val, 0.05, max_val), 
                           labels = c(round(min_val), 0.05, round(max_val))) + 
      coord_fixed() + 
      ggtitle("MST: Differential expression (DE) test results") + 
      theme_bw()
    
    ggsave(file.path(path, "MST_results_DE.pdf"), width = 10, height = 10)
  }
}


