#' Plot minimum spanning tree (MST)
#' 
#' Plot minimum spanning tree (MST) from FlowSOM clustering
#' 
#' Creates a minimum spanning tree (MST) plot showing the relationship between clusters 
#' generated by FlowSOM.
#' 
#' This function generates a basic MST plot. Cluster sizes are scaled by the total number 
#' of cells per cluster.
#' 
#' Additional functions are available for MST plots that also display results from the 
#' differential expression tests.
#' 
#' 
#' @param d_se Data object from \code{\link{generateClusters}}, which contains the minimum
#'   spanning tree (MST) information from the FlowSOM clustering algorithm.
#' 
#' @param d_counts Data object from \code{\link{calcCounts}}, which contains the number of
#'   cells per cluster.
#' 
#' @param path Path to save plot. Default = current working directory.
#' 
#' 
#' @importFrom S4Vectors metadata
#' @importFrom SummarizedExperiment rowData
#' @importFrom ggplot2 ggplot aes geom_point coord_fixed ggtitle theme_bw ggsave
#' 
#' @export
#' 
#' @seealso \code{\link{testDA}} \code{\link{testDE_med}} \code{\link{testDE_FDA}}
#'   \code{\link{testDE_KS}} \code{\link{testDE_LM}}
#'
#' @examples
#' # See full examples in testing functions: testDA, testDE_med, testDE_FDA, testDE_KS,
#' # testDE_LM
#' 
plotMST <- function(d_se, d_counts, path = ".") {
  
  mst <- metadata(d_se)$MST
  
  mst_coords <- mst$l
  
  if (!(nrow(mst_coords) == length(rowData(d_counts)$cluster))) {
    stop("minimum spanning tree (MST) does not have correct number of clusters")
  }
  
  n_cells <- rowData(d_counts)$n_cells
  
  d_plot <- data.frame(mst_coords)
  colnames(d_plot) <- c("MST_x", "MST_y")
  
  ggplot(d_plot, aes(x = MST_x, y = MST_y, size = n_cells)) + 
    geom_point(alpha = 0.5, color = "darkblue") + 
    coord_fixed() + 
    ggtitle("FlowSOM clustering: minimum spanning tree") + 
    theme_bw()
  
  ggsave(file.path(path, "clusters_MST.pdf"), width = 6, height = 6)
}


